/**
 * movie genre fetch
 */
export const GET_MOVIE_GENRE_REQUEST = 'GET_MOVIE_GENRE_REQUEST';
export const GET_MOVIE_GENRE_SUCCEEDED = 'GET_MOVIE_GENRE_SUCCEEDED';
export const GET_MOVIE_GENRE_FAILED = 'GET_MOVIE_GENRE_FAILED';

/**
 * seats fetch action
 */
export const GET_SEATS_REQUEST = 'GET_SEATS_REQUEST';
export const GET_SEATS_SUCCEEDED = 'GET_SEATS_SUCCEEDED';
export const GET_SEATS_FAILED = 'GET_SEATS_FAILED';
