/**
 * movie genre fetch
 */
export const GET_MOVIE_GENRE_REQUEST = 'GET_MOVIE_GENRE_REQUEST';
export const GET_MOVIE_GENRE_SUCCEEDED = 'GET_MOVIE_GENRE_SUCCEEDED';
export const GET_MOVIE_GENRE_FAILED = 'GET_MOVIE_GENRE_FAILED';

/**
 * seats fetch action
 */
export const GET_SEATS_REQUEST = 'GET_SEATS_REQUEST';
export const GET_SEATS_SUCCEEDED = 'GET_SEATS_SUCCEEDED';
export const GET_SEATS_FAILED = 'GET_SEATS_FAILED';

/**
 * book seats action
 */

export const TOGGLE_SEAT_BOOKING_REQUEST = 'TOGGLE_SEAT_BOOKING_REQUEST';
export const TOGGLE_SEAT_BOOKING_SUCCEEDED = 'TOGGLE_SEAT_BOOKING_SUCCEEDED';
export const SEAT_NOT_AVAILABLE = 'SEAT_NOT_AVAILABLE';
export const TOGGLE_SEAT_BOOKING_FAILED = 'TOGGLE_SEAT_BOOKING_FAILED';
